# Generated by Django 4.1.5 on 2023-02-10 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=1, max_digits=20)),
                ('last_updated', models.DateTimeField(verbose_name='Last Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date recorded')),
                ('opening_price', models.DecimalField(decimal_places=1, max_digits=20)),
                ('closing_price', models.DecimalField(decimal_places=1, max_digits=20)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.stock')),
            ],
        ),
    ]
