# Generated by Django 4.1.5 on 2023-02-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_stock_stock_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp500_tickers', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='name',
            new_name='company_name',
        ),
    ]
