# Generated by Django 4.1.5 on 2023-02-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_tickers_rename_name_stock_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickers',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
        ),
    ]
